logging:
  level:
    io.lettuce.core: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
spring:
  redis:
    sentinel:
      master: mymaster
      nodes:
        - 192.168.111.100:26379
        - 192.168.111.100:26380
        - 192.168.111.100:26381